import Vue from 'vue'
import {
	Button,
	Select,
	Option,
	Form,
	FormItem,
	Input,
	Icon,
	Container,
	Header,
	Aside,
	Main,
	Footer,
	Menu,
	MenuItem,
	Submenu,
	Breadcrumb,
	BreadcrumbItem,
	Card,
	Row,
	Col,
	Table,
	TableColumn,
	Dialog,
	Pagination,
	RadioGroup,
	RadioButton,
	DatePicker,
	Message,
	Popover,
	Loading,
	Divider,
	Checkbox,
	CheckboxGroup,
	TimePicker,
	ButtonGroup,
	Radio,
	Backtop,
	Drawer,
	Tabs,
	TabPane,
	Image,
	Transfer
} from 'element-ui'
import 'element-ui/lib/theme-chalk/index.css'
import 'element-ui/lib/theme-chalk/display.css'

Vue.prototype.$message = Message
Vue.use(Button)
Vue.use(Select)
Vue.use(Option)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Icon)
Vue.use(Container)
Vue.use(Header)
Vue.use(Aside)
Vue.use(Main)
Vue.use(Footer)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Submenu)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Card)
Vue.use(Row)
Vue.use(Col)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Dialog)
Vue.use(Pagination)
Vue.use(RadioGroup)
Vue.use(RadioButton)
Vue.use(DatePicker)
Vue.use(Popover)
Vue.use(Loading)
Vue.use(Divider)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(TimePicker)
Vue.use(ButtonGroup)
Vue.use(Radio)
Vue.use(Backtop)
Vue.use(Drawer)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Image)
Vue.use(Transfer)
